#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the first argument, like:
#           sh myscript
#       For example: '/bin/bash gradlew' or 'ksh gradlew'
#
#       The 'cygwin' and 'msys' environments are known to be noncompliant.
#
#   (2) This script points to the Java runtime that executes Gradle. It uses
#       the value of the JAVA_HOME environment variable to find the Java
#       installation. If Java isn't available, it will download a compatible
#       Java runtime and use that instead.
#
#   (3) You may need to pass JVM arguments to this script, depending on your
#       environment. For example, to limit memory usage for Gradle:
#           ./gradlew -Dorg.gradle.jvmargs="-Xmx2048m"
#
#       You can find more information about available JVM arguments at:
#       https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_jvm_args
#
#   (4) If you don't need network connectivity, you can prevent any external
#       requests to check for newer Gradle versions by setting the 'org.gradle.disable.auto.version.caching'
#       system property:
#           ./gradlew -Dorg.gradle.disable.auto.version.caching=true
#
#   (5) For Unix-like systems, this script uses tar to unpack the downloaded
#       Gradle distribution. If tar is unavailable, it will attempt to download
#       a zip distribution.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s' "$PWD" ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H -n is unknown. Use prlimit if available, or fallback to ulimit after checking it's a valid option.
        if command -v prlimit >/dev/null 2>&1; then
            prlimit --pid=$$ --nofile=hard
            PRLIMIT_EXIT=$?
            if [ $PRLIMIT_EXIT -eq 0 ]; then
                ulimit -n hard
            else
                echo "prlimit failed, falling back to ulimit" >&2
                # POSIX sh doesn't know '-n' as an option to ulimit. If it's available and we ask for it, expect it to work.
                if ulimit -n >/dev/null 2>&1; then
                    ulimit -n hard
                fi
            fi
        else
            # POSIX sh doesn't know '-n' as an option to ulimit. If it's available and we ask for it, expect it to work.
            if ulimit -n >/dev/null 2>&1; then
                ulimit -n hard
            fi
        fi
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module added)
#   * --module-path entries
#   * --add-modules (for modular jars)

# The Java main class to execute (this class loads the Gradle distribution)
MAIN_CLASS=org.gradle.wrapper.GradleWrapperMain

# Collect all arguments for the java command;
#   * $APP_HOME/gradle/wrapper/gradle-wrapper.jar is added to the classpath
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain arguments
#     that are passed to the Java executable.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect JVM arguments (don't add to command line array if they are also needed elsewhere)
if [ -n "$JAVA_OPTS" ] ; then
    DEFAULT_JVM_OPTS="$JAVA_OPTS $DEFAULT_JVM_OPTS"
fi
if [ -n "$GRADLE_OPTS" ] ; then
    DEFAULT_JVM_OPTS="$GRADLE_OPTS $DEFAULT_JVM_OPTS"
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - sh-compatible escaping
    # We build the set of arguments by looping through the original raw args,
    # substituting each with its cygwin/mingw converted form, escaping as necessary,
    # and appending the result to the target array.
    set -- "$DEFAULT_JVM_OPTS" "$@"
    target=
    for i in "$@"; do
        case $i in
            (--module-path=*)
                target="$target $i" ;;
            (-D*)
                target="$target $i" ;;
            (*)
                # accept anything that looks like a Java argument; only the main class and -classpath will be handled by the wrapper.
                if [ "${i#-}" != "$i" ]; then
                    target="$target $i"
                else
                    # If we're in a non-POSIX shell, we need to escape double quotes and backslashes.
                    if ! (command -v getopt >/dev/null 2>&1 && getopt --version 2>&1 | grep -q 'enhanced'); then
                        case $i in
                            (*[!\"]*)
                                target="$target \"$i\"" ;;
                            (*)
                                target="$target $i" ;;
                        esac
                    else
                        target="$target $i"
                    fi
                fi
                ;;
        esac
    done
    set -- $target
fi

# Evaluate the arguments, joining them on spaces and appending the main class
# Note: In POSIX sh, "$@" will expand to all arguments, preserving quoting.
eval "set -- $(
    printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
    xargs |
    printf '%s' '"--classpath" "$CLASSPATH" "$MAIN_CLASS" "$@"'
)"

# Run the wrapper (this is the main Gradle command that will run the wrapper script itself if needed)
exec "$JAVACMD" "$@"